version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/src:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - match-serve
    links:
      - match-serve
    networks:
      - app_net

  match-serve:
    build:
      context: ./../match_day_serve
    environment:
      POCKETBASE_URL: "http://192.168.1.15:8090"
    ports:
      - "8086:8086"
    networks:
      - app_net

networks:
  app_net:
    driver: bridge